name: .NET

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    BRANCH_NAME: ${GITHUB_REF#refs/heads/}
    MAJOR_VERSION: 1
    MINOR_VERSION: 0
    PATCH_VERSION: 0
    BUILD_VERSION: $MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION.${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Show build number
      run: echo ${{ env.BUILD_VERSION }}

    - name: Show branch name
      run: echo ${{ env.BRANCH_NAME }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Restore dependencies
      run: dotnet restore ./src

    - name: Build
      run: dotnet build ./src --no-restore --configuration "Release" -p:Version=$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION.$REV_VERSION

    - name: Test
      run: dotnet test ./src --no-build --no-restore --configuration "Release"

    - name: Pack
      run: dotnet pack ./src --no-build --no-restore --configuration "Release" -p:NuspecFile=$GITHUB_WORKSPACE/build/Shared.WebApi.Core.nuspec -p:NuspecBasePath=$GITHUB_WORKSPACE/src -p:Version=$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION.$REV_VERSION

    - name: Push
      run:  dotnet nuget push "$GITHUB_WORKSPACE/src/Shared.WebApi.Core/bin/Release/Shared.WebApi.Core.*.nupkg" --source "https://nuget.pkg.github.com/krylixza/index.json" --skip-duplicate --api-key $GITHUB_TOKEN

    - name: Run SonarQube Scan
      uses: highbyte/sonarscan-dotnet@1.0.2
      with:
        sonarProjectKey: Shared-WebApi-Core
        sonarProjectName:  Shared-WebApi-Core
        sonarOrganization: krylixza
        dotnetBuildArguments: ./src
        dotnetTestArguments: ./src --logger trx --output "../TestResults/" -p:CollectCoverage=true -p:CoverletOutputFormat="json%2copencover" -p:CoverletOutput="../TestResults/" -p:MergeWith="../TestResults/coverage.json"
        sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"
